[Display]
fDefaultWorldFOV=85.0000
fDefault1stPersonFOV=75.0000
fPipboy1stPersonFOV=43.0000
fRenderedTerminalFOV=0.1550
;fScopeScissorAmount=0.2500
; https://www.nexusmods.com/newvegas/mods/71781
fScopeScissorAmount=0
fWeaponFOVRatio=40.0000
bNoWeaponZoom=0.0000
;bNoScopeScissor=0.0000
; https://www.nexusmods.com/newvegas/mods/71781
bNoScopeScissor=1
fIronSightsFOVTimeChange=0.1000
fDialogZoomInSeconds=1.5000
fDialogZoomOutSeconds=0.5000
fDialogSpeechDelaySeconds=2.0000
fNearDistance=4.3000
