; DLC: Anchorage, don't loot simulated NPCs
$DLC02AmericanFlamer1TEMPLATE
$DLC02AmericanFlamer2
$DLC02AmericanFlamer3
$DLC02AmericanFlamer4
$DLC02AmericanFlamer5
$DLC02AmericanMissileLauncher1TEMPLATE
$DLC02AmericanMissileLauncher2
$DLC02AmericanMissileLauncher3
$DLC02AmericanMissileLauncher4
$DLC02AmericanMissileLauncher5
$DLC02AmericanSniper1TEMPLATE
$DLC02AmericanSniper2
$DLC02AmericanSniper3
$DLC02AmericanSniper4
$DLC02AmericanSniper5
$DLC02AmericanSoldier1TEMPLATE
$DLC02AmericanSoldier2
$DLC02AmericanSoldier3
$DLC02AmericanSoldier4
$DLC02AmericanSoldier5
$DLC02AmericanSoldierArtilleryTarget
$DLC02AmericanSoldierBackupRunNGuard
$DLC02AmericanTrenchClimber
$DLC02ArtyBaseChineseEscortTank
$DLC02ArtyBaseChineseTravel
$DLC02ArtyBaseCrimsonDragoon01
$DLC02ArtyBaseCrimsonDragoon02
$DLC02ArtyBaseCrimsonDragoon03
